apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql #this label needs to refer to a Pod (a Pod, not a Deployment!)
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None # this means we are going to use the Pod IP instead of creating a new IP (as only one pod will run anyhow)
